/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkMode: typeof import('./src/components/Navigate/DarkMode.vue')['default']
    MacOS: typeof import('./src/components/Titlebar/MacOS.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Navigate: typeof import('./src/components/Navigate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    User: typeof import('./src/components/Navigate/User.vue')['default']
    UserInfo: typeof import('./src/components/Navigate/User/UserInfo.vue')['default']
    Windows: typeof import('./src/components/Titlebar/Windows.vue')['default']
  }
}
