/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MacOS: typeof import('./src/components/Titlebar/MacOS.vue')['default']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
    Windows: typeof import('./src/components/Titlebar/Windows.vue')['default']
  }
}
