/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkMode: typeof import('./src/components/Navigate/DarkMode.vue')['default']
    MacOS: typeof import('./src/components/Titlebar/MacOS.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Navigate: typeof import('./src/components/Navigate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
    Windows: typeof import('./src/components/Titlebar/Windows.vue')['default']
  }
}
